export * from "./DashboardIcon";
export * from "./MessageIcon";
export * from "./SettingsIcon";
export * from "./UserIcon";
export * from './AcademicIcon'
export * from './AdminsIcon'
export * from './StaffsIcon'
export * from './RefreshIcon'
export * from './AuthenticatorIcon'
export * from './PeopleIcon'
export * from './NitdaLogo'