"use client";
import { Button, Header } from "@/components/custom-ui";
import { AuthenticatorIcon } from "public/icons";

const TwoStepAuthentication = () => {
    return (
        <main>
            <div className="mb-10">
                <Header message="Two factor authentication" className="mb-2" />
                <p className="text-sm font-normal text-[#797979]">
                    Use google authenticator to secure your account and receive a secure verification code{" "}
                </p>
            </div>
            <div className="flex flex-col flex-wrap md:flex-row">
                <div className="min-w-[400px] rounded-[5px] bg-white px-4 py-4 shadow-md">
                    <h2 className="w-full border-b border-b-[#C3C3CB] pb-4 text-center text-base font-semibold text-[#272727]">
                        Google Authenticator
                    </h2>
                    <div className="mt-5 flex flex-col items-center gap-3">
                        <AuthenticatorIcon />

                        <p className="mb-4 text-center text-sm font-normal text-[#272727]">
                            Security codes will be generated by \Google Authenticator
                        </p>

                        <Button variant="contained" label="Use Google Authenticator" />
                    </div>
                </div>
            </div>
        </main>
    );
};

export default TwoStepAuthentication;
