export const QUOTES = [
    "A man who swallows a whole coconut has complete faith in his anus.",
    "No matter how much the buttocks are in a hurry, they will always remain behind.",
    "Yansh no get razor but he dey cut the shit.",
    "Nigeria was never on the map when God said, 'Let there be light….'",
    "Drinking garri does not mean you’re poor but allowing your garri to soak is poverty.",
    "Sapa good one, even what goes around no see transport come back.",
    "Never open the door for an Armed Robber, let them break it, it’s part of their job.",
    "One Man’s food is every other man’s food, just because one idiot refuses to eat it doesn’t make it poison.",
    "He who says nothing lasts forever has never tried Hausa perfume.",
    "He who runs around looking for scissors to cut Indomie seasoning sachets is not yet hungry.",
    "Of course, if women ruled the whole world, there would be no wars because it would be just a bunch of jealous countries not talking to each other.",
    "A child can play with its mother’s breasts, but not its father’s testicles.",
    "There is no greater injustice than when the anus farts, the head receives a knock.",
    "God made everything that has life; everything else is made in China.",
    "The frown on the face of a goat will not stop it from being priced in the market.",
    "Treat every part of your towel nicely because the part that wipes your yansh today will wipe your face tomorrow.",
    "I’m not lazy, I just rest before I get tired.",
    "It is better to remain silent at the risk of being thought a fool.",
    "Knowing yourself is the beginning of all wisdom.",
    "Stupidity is what we all have in common as human beings, but some people insist that improving it is their entitlement.",
    "If people have a problem with you, always remember that it is THEIR problem.",
    "Do not look where you fell, but where you slipped.",
    "Sometimes you have to play the role of a fool to fool the fools who think they are fooling you.",
    "A wise person knows that there is something to be learned from everyone.",
    "The wolf on the hill is not as hungry as the wolf climbing the hill.",
    "It requires a lot of carefulness to kill the fly that perches on the scrotum.",
    "Snails don’t venture where horned animals gather.",
    "My brother hustle oh!! Make you no come dey explain the nutritional value of stale soup to your children! – Sound Sultan.",
    "Never allow the perception of others to play a substantial part in your own vision of yourself and your future. – Jim Ovia.",
    "Falling down is inevitable but getting back up is optional.",
    "You can appreciate sunshine if you have never been through heavy rain.",
    "Cut out the noise, focus on doing the right thing, making an impact in opening doors for others to come.",
    "Your speed in life is mostly determined by what is chasing you.",
    "If you don’t have ambition, you shouldn’t be alive.",
];
